version: '2.1'
services:
  device:
    container_name: device
    image: device
    volumes:
      - "./files:/tmp/files"
    build: ./device
    ports:
      - "8082:8082"
    depends_on:
      - discovery
  discovery:
    container_name: discovery
    image: discovery
    volumes:
      - "./files:/tmp/files"
    build: ./discovery
    ports:
      - "8081:8081"