server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: device
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect        
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:device
    driverClassName: org.h2.Driver
    username: sa
    password: password

springdoc:
  swagger-ui:
    path: /api-doc.html